name: Lint & Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        name: Set up python
      - name: Install pipenv
        run: pip install --upgrade pipenv --user
      - name: Install ruff
        run: pipenv install --dev ruff
      - name: Run ruff
        run: pipenv run ruff check --verbose

  test:
    name: Unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        name: Set up python
      - name: Install pipenv
        run: pip install --upgrade pipenv --user
#      - name: Sync your dependencies
#        run: pipenv sync --categories="extra"
#      - name: Install package
#        run: pipenv run pip install .[like]
      - name: Run unittest
        run: pipenv run python -m unittest
